version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-passw0rd}@mongo:27017/colman_db?authSource=admin
      - PORT=3000
      - DAL_TYPE=mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: colman-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-passw0rd}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-colman_db}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
